/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.112
 * Generated at: 2025-12-07 14:19:57 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.pages.books;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

 
    ResultSet readBook(Connection conn, Statement stmt, String url) throws Exception {
        String query = "SELECT * FROM book";
        return stmt.executeQuery(query); 
    }

 
    String createBook(
        Connection conn, 
        String image, 
        String name, 
        String description, 
        String content
    ) throws Exception {
        String result = "";

        try {
            if (conn != null && !conn.isClosed()) {
                String sql = "INSERT INTO book (image, name, description, content) VALUES (?, ?, ?, ?)";
                try (PreparedStatement pstmt = conn.prepareStatement(sql)) {
                    pstmt.setString(1, image);
                    pstmt.setString(2, name);
                    pstmt.setString(3, description);
                    pstmt.setString(4, content);

                    int rowsAffected = pstmt.executeUpdate();

                    if (rowsAffected > 0) {
                        result = "Livro inserido com sucesso!";
                    } else {
                        result = "Nenhum livro foi inserido.";
                    }
                }
            } else {
                result = "ConexÃ£o com o banco nÃ£o estÃ¡ disponÃ­vel.";
            }
        } catch (SQLException e) {
            result = "Erro ao inserir livro: " + e.getMessage();
        }
        return result;
    }

 
    String test(Connection conn, Statement stmt, String image, 
        String name, String description, String content) {
        return "teste";
    }


  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/src/config/connect.jsp", Long.valueOf(1765116736165L));
    _jspx_dependants.put("/src/repository/book/book.jsp", Long.valueOf(1765117196203L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(6);
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");

    String path = application.getRealPath("/");
    String clean = path.replace("\\", "/");
    String url = "jdbc:sqlite:" + clean + "banco.db";
    Connection conn = null;
    Statement stmt = null;
    Class.forName("org.sqlite.JDBC");
    conn = DriverManager.getConnection(url);
    stmt = conn.createStatement();

    Connection connCreate = DriverManager.getConnection(url);
    Statement stmtCreate = conn.createStatement();

      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

    ResultSet read = readBook(conn, stmt, url);

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"pt-BR\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>Sistema de Livros - CRUD</title>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/books.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("        <div class=\"header\">\r\n");
      out.write("            <h1>📚 Sistema de Gestão de Livros</h1>\r\n");
      out.write("            <button class=\"btn btn-primary btn-lg\" onclick=\"openCreateModal()\">\r\n");
      out.write("                ➕ Novo Livro\r\n");
      out.write("            </button>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <!-- Mensagens de Feedback -->\r\n");
      out.write("        <div id=\"successMessage\" class=\"alert alert-success\" style=\"display: none;\"></div>\r\n");
      out.write("        <div id=\"errorMessage\" class=\"alert alert-danger\" style=\"display: none;\"></div>\r\n");
      out.write("\r\n");
      out.write("        <!-- Tabela de Livros -->\r\n");
      out.write("        <div class=\"books-container\">\r\n");
      out.write("            <table class=\"books-table\">\r\n");
      out.write("                <thead>\r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <th>ID</th>\r\n");
      out.write("                        <th>Imagem</th>\r\n");
      out.write("                        <th>Nome</th>\r\n");
      out.write("                        <th>Descrição</th>\r\n");
      out.write("                        <th>Conteúdo</th>\r\n");
      out.write("                        <th>Ações</th>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                </thead>\r\n");
      out.write("                <tbody id=\"booksTableBody\">\r\n");
      out.write("                    ");

                        try {
                            if (read != null) {
                                while (read.next()) {
                    
      out.write("\r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <td>");
      out.print( read.getInt("id") );
      out.write("</td>\r\n");
      out.write("                        <td>\r\n");
      out.write("                            ");
 String image = read.getString("image"); 
      out.write("\r\n");
      out.write("                            ");
 if (image != null && !image.isEmpty()) { 
      out.write("\r\n");
      out.write("                                <img src=\"");
      out.print( image );
      out.write("\" alt=\"");
      out.print( read.getString("name") );
      out.write("\" class=\"book-thumbnail\">\r\n");
      out.write("                            ");
 } else { 
      out.write("\r\n");
      out.write("                                <span class=\"no-image\">Sem imagem</span>\r\n");
      out.write("                            ");
 } 
      out.write("\r\n");
      out.write("                        </td>\r\n");
      out.write("                        <td><strong>");
      out.print( read.getString("name") );
      out.write("</strong></td>\r\n");
      out.write("                        <td>");
      out.print( read.getString("description") );
      out.write("</td>\r\n");
      out.write("                        <td>");
      out.print( read.getString("content") );
      out.write("</td>\r\n");
      out.write("                        <td>\r\n");
      out.write("                            <button class=\"btn btn-info btn-sm\" \r\n");
      out.write("                                    onclick=\"openUpdateModal(\r\n");
      out.write("                                        ");
      out.print( read.getInt("id") );
      out.write(", \r\n");
      out.write("                                        '");
      out.print( read.getString("image") );
      out.write("', \r\n");
      out.write("                                        '");
      out.print( read.getString("name").replace("'", "\\'") );
      out.write("', \r\n");
      out.write("                                        '");
      out.print( read.getString("description").replace("'", "\\'") );
      out.write("', \r\n");
      out.write("                                        '");
      out.print( read.getString("content").replace("'", "\\'") );
      out.write("'\r\n");
      out.write("                                    )\">\r\n");
      out.write("                                ✏️ Editar\r\n");
      out.write("                            </button>\r\n");
      out.write("                            <button class=\"btn btn-danger btn-sm\" \r\n");
      out.write("                                    onclick=\"deleteBook(");
      out.print( read.getInt("id") );
      out.write(")\">\r\n");
      out.write("                                🗑️ Deletar\r\n");
      out.write("                            </button>\r\n");
      out.write("                        </td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                    ");

                                }
                            }
                        } catch (Exception e) {
                    
      out.write("\r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <td colspan=\"6\" class=\"error-message\">\r\n");
      out.write("                            Erro ao carregar livros: ");
      out.print( e.getMessage() );
      out.write("\r\n");
      out.write("                        </td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                    ");

                        }
                    
      out.write("\r\n");
      out.write("                </tbody>\r\n");
      out.write("            </table>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <!-- Modal para Criar Livro -->\r\n");
      out.write("    <div id=\"createModal\" class=\"modal\">\r\n");
      out.write("        <div class=\"modal-content\">\r\n");
      out.write("            <span class=\"close\" onclick=\"closeCreateModal()\">&times;</span>\r\n");
      out.write("            <h2>Adicionar Novo Livro</h2>\r\n");
      out.write("            <div id=\"createBookForm\">\r\n");
      out.write("                <div class=\"form-group\">\r\n");
      out.write("                    <label for=\"createImage\">URL da Imagem:</label>\r\n");
      out.write("                    <input type=\"url\" id=\"createImage\" name=\"image\" placeholder=\"https://exemplo.com/imagem.jpg\" required>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"form-group\">\r\n");
      out.write("                    <label for=\"createName\">Nome do Livro:</label>\r\n");
      out.write("                    <input type=\"text\" id=\"createName\" name=\"name\" placeholder=\"Digite o nome do livro\" required>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"form-group\">\r\n");
      out.write("                    <label for=\"createDescription\">Descrição:</label>\r\n");
      out.write("                    <textarea id=\"createDescription\" name=\"description\" placeholder=\"Descrição breve do livro\" rows=\"3\" required></textarea>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"form-group\">\r\n");
      out.write("                    <label for=\"createContent\">Conteúdo:</label>\r\n");
      out.write("                    <textarea id=\"createContent\" name=\"content\" placeholder=\"Conteúdo completo do livro\" rows=\"5\" required></textarea>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"form-actions\">\r\n");
      out.write("                    <button onclick=\"submitCreateForm()\" class=\"btn btn-success\">💾 Salvar Livro</button>\r\n");
      out.write("                    <button type=\"button\" class=\"btn btn-secondary\" onclick=\"closeCreateModal()\">Cancelar</button>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <!-- Modal para Atualizar Livro -->\r\n");
      out.write("    <div id=\"updateModal\" class=\"modal\">\r\n");
      out.write("        <div class=\"modal-content\">\r\n");
      out.write("            <span class=\"close\" onclick=\"closeUpdateModal()\">&times;</span>\r\n");
      out.write("            <h2>Editar Livro</h2>\r\n");
      out.write("            <form id=\"updateBookForm\" onsubmit=\"submitUpdateForm(event)\">\r\n");
      out.write("                <input type=\"hidden\" id=\"updateId\" name=\"id\">\r\n");
      out.write("\r\n");
      out.write("                <div class=\"form-group\">\r\n");
      out.write("                    <label for=\"updateImage\">URL da Imagem:</label>\r\n");
      out.write("                    <input type=\"url\" id=\"updateImage\" name=\"image\" placeholder=\"https://exemplo.com/imagem.jpg\" required>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"form-group\">\r\n");
      out.write("                    <label for=\"updateName\">Nome do Livro:</label>\r\n");
      out.write("                    <input type=\"text\" id=\"updateName\" name=\"name\" placeholder=\"Digite o nome do livro\" required>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"form-group\">\r\n");
      out.write("                    <label for=\"updateDescription\">Descrição:</label>\r\n");
      out.write("                    <textarea id=\"updateDescription\" name=\"description\" placeholder=\"Descrição breve do livro\" rows=\"3\" required></textarea>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"form-group\">\r\n");
      out.write("                    <label for=\"updateContent\">Conteúdo:</label>\r\n");
      out.write("                    <textarea id=\"updateContent\" name=\"content\" placeholder=\"Conteúdo completo do livro\" rows=\"5\" required></textarea>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"form-actions\">\r\n");
      out.write("                    <button type=\"submit\" class=\"btn btn-success\">💾 Atualizar Livro</button>\r\n");
      out.write("                    <button type=\"button\" class=\"btn btn-secondary\" onclick=\"closeUpdateModal()\">Cancelar</button>\r\n");
      out.write("                </div>\r\n");
      out.write("            </form>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <!-- Modal de Confirmação de Exclusão -->\r\n");
      out.write("    <div id=\"deleteModal\" class=\"modal\">\r\n");
      out.write("        <div class=\"modal-content modal-confirmation\">\r\n");
      out.write("            <h2>Confirmar Exclusão</h2>\r\n");
      out.write("            <p>Tem certeza de que deseja deletar este livro?</p>\r\n");
      out.write("            <p class=\"warning\">Esta ação não pode ser desfeita.</p>\r\n");
      out.write("            <div class=\"form-actions\">\r\n");
      out.write("                <button class=\"btn btn-danger\" onclick=\"confirmDelete()\">🗑️ Sim, Deletar</button>\r\n");
      out.write("                <button class=\"btn btn-secondary\" onclick=\"cancelDelete()\">Cancelar</button>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <script>\r\n");
      out.write("        // API Handler URL\r\n");
      out.write("        const API_HANDLER = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/api/bookHandler.jsp\";\r\n");
      out.write("    </script>\r\n");
      out.write("    <script>\r\n");
      out.write("    // ==================== Modal Management ====================\r\n");
      out.write("\r\n");
      out.write("function openCreateModal() {\r\n");
      out.write("    const modal = document.getElementById(\"createModal\");\r\n");
      out.write("    modal.style.display = \"block\";\r\n");
      out.write("    document.getElementById(\"createBookForm\").reset();\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function closeCreateModal() {\r\n");
      out.write("    const modal = document.getElementById(\"createModal\");\r\n");
      out.write("    modal.style.display = \"none\";\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function openUpdateModal(id, image, name, description, content) {\r\n");
      out.write("    const modal = document.getElementById(\"updateModal\");\r\n");
      out.write("    modal.style.display = \"block\";\r\n");
      out.write("\r\n");
      out.write("    document.getElementById(\"updateId\").value = id;\r\n");
      out.write("    document.getElementById(\"updateImage\").value = decodeURIComponent(image);\r\n");
      out.write("    document.getElementById(\"updateName\").value = decodeURIComponent(name);\r\n");
      out.write("    document.getElementById(\"updateDescription\").value = decodeURIComponent(description);\r\n");
      out.write("    document.getElementById(\"updateContent\").value = decodeURIComponent(content);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function closeUpdateModal() {\r\n");
      out.write("    const modal = document.getElementById(\"updateModal\");\r\n");
      out.write("    modal.style.display = \"none\";\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("// ==================== Delete Modal ====================\r\n");
      out.write("let deleteBookId = null;\r\n");
      out.write("\r\n");
      out.write("function deleteBook(id) {\r\n");
      out.write("    deleteBookId = id;\r\n");
      out.write("    const modal = document.getElementById(\"deleteModal\");\r\n");
      out.write("    modal.style.display = \"block\";\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function confirmDelete() {\r\n");
      out.write("    if (deleteBookId === null) return;\r\n");
      out.write("\r\n");
      out.write("    const formData = new FormData();\r\n");
      out.write("    formData.append(\"action\", \"delete\");\r\n");
      out.write("    formData.append(\"id\", deleteBookId);\r\n");
      out.write("\r\n");
      out.write("    fetch(API_HANDLER, {\r\n");
      out.write("        method: \"POST\",\r\n");
      out.write("        body: formData\r\n");
      out.write("    })\r\n");
      out.write("        .then((response) => response.json())\r\n");
      out.write("        .then((data) => {\r\n");
      out.write("            if (data.success) {\r\n");
      out.write("                showSuccessMessage(\"Livro deletado com sucesso!\");\r\n");
      out.write("                setTimeout(() => {\r\n");
      out.write("                    location.reload();\r\n");
      out.write("                }, 1500);\r\n");
      out.write("            } else {\r\n");
      out.write("                showErrorMessage(data.message);\r\n");
      out.write("            }\r\n");
      out.write("        })\r\n");
      out.write("        .catch((error) => {\r\n");
      out.write("            showErrorMessage(\"Erro ao deletar livro: \" + error);\r\n");
      out.write("            console.error(\"Erro:\", error);\r\n");
      out.write("        })\r\n");
      out.write("        .finally(() => {\r\n");
      out.write("            cancelDelete();\r\n");
      out.write("        });\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function cancelDelete() {\r\n");
      out.write("    deleteBookId = null;\r\n");
      out.write("    const modal = document.getElementById(\"deleteModal\");\r\n");
      out.write("    modal.style.display = \"none\";\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("// ==================== Form Submission ====================\r\n");
      out.write("\r\n");
      out.write("function submitCreateForm(event) {\r\n");
      out.write("  /*  event.preventDefault();\r\n");
      out.write("\r\n");
      out.write("    const form = document.getElementById(\"createBookForm\");\r\n");
      out.write("    const formData = new FormData(form);\r\n");
      out.write("    formData.append(\"action\", \"create\");\r\n");
      out.write("\r\n");
      out.write("    fetch(API_HANDLER, {\r\n");
      out.write("        method: \"POST\",\r\n");
      out.write("        body: formData\r\n");
      out.write("    })\r\n");
      out.write("        .then((response) => response.json())\r\n");
      out.write("        .then((data) => {\r\n");
      out.write("            if (data.success) {\r\n");
      out.write("                showSuccessMessage(\"Livro criado com sucesso!\");\r\n");
      out.write("                closeCreateModal();\r\n");
      out.write("                setTimeout(() => {\r\n");
      out.write("                    location.reload();\r\n");
      out.write("                }, 1500);\r\n");
      out.write("            } else {\r\n");
      out.write("                showErrorMessage(data.message);\r\n");
      out.write("            }\r\n");
      out.write("        })\r\n");
      out.write("        .catch((error) => {\r\n");
      out.write("            showErrorMessage(\"Erro ao criar livro: \" + error);\r\n");
      out.write("            console.error(\"Erro:\", error);\r\n");
      out.write("        }); */\r\n");
      out.write("\r\n");
      out.write("alert(\"");
      out.print( createBook(connCreate, "agora vai 2", "agora vai", "agora vai", "agora vai") );
      out.write("\") \r\n");
      out.write("   \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function submitUpdateForm(event) {\r\n");
      out.write("    event.preventDefault();\r\n");
      out.write("\r\n");
      out.write("    const form = document.getElementById(\"updateBookForm\");\r\n");
      out.write("    const formData = new FormData(form);\r\n");
      out.write("    formData.append(\"action\", \"update\");\r\n");
      out.write("\r\n");
      out.write("    fetch(API_HANDLER, {\r\n");
      out.write("        method: \"POST\",\r\n");
      out.write("        body: formData\r\n");
      out.write("    })\r\n");
      out.write("        .then((response) => response.json())\r\n");
      out.write("        .then((data) => {\r\n");
      out.write("            if (data.success) {\r\n");
      out.write("                showSuccessMessage(\"Livro atualizado com sucesso!\");\r\n");
      out.write("                closeUpdateModal();\r\n");
      out.write("                setTimeout(() => {\r\n");
      out.write("                    location.reload();\r\n");
      out.write("                }, 1500);\r\n");
      out.write("            } else {\r\n");
      out.write("                showErrorMessage(data.message);\r\n");
      out.write("            }\r\n");
      out.write("        })\r\n");
      out.write("        .catch((error) => {\r\n");
      out.write("            showErrorMessage(\"Erro ao atualizar livro: \" + error);\r\n");
      out.write("            console.error(\"Erro:\", error);\r\n");
      out.write("        });\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("// ==================== Message Handling ====================\r\n");
      out.write("\r\n");
      out.write("function showSuccessMessage(message) {\r\n");
      out.write("    const messageDiv = document.getElementById(\"successMessage\");\r\n");
      out.write("    messageDiv.textContent = message;\r\n");
      out.write("    messageDiv.style.display = \"block\";\r\n");
      out.write("    setTimeout(() => {\r\n");
      out.write("        messageDiv.style.display = \"none\";\r\n");
      out.write("    }, 4000);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function showErrorMessage(message) {\r\n");
      out.write("    const messageDiv = document.getElementById(\"errorMessage\");\r\n");
      out.write("    messageDiv.textContent = message;\r\n");
      out.write("    messageDiv.style.display = \"block\";\r\n");
      out.write("    setTimeout(() => {\r\n");
      out.write("        messageDiv.style.display = \"none\";\r\n");
      out.write("    }, 4000);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("// ==================== Modal Close on Outside Click ====================\r\n");
      out.write("\r\n");
      out.write("window.onclick = function (event) {\r\n");
      out.write("    const createModal = document.getElementById(\"createModal\");\r\n");
      out.write("    const updateModal = document.getElementById(\"updateModal\");\r\n");
      out.write("    const deleteModal = document.getElementById(\"deleteModal\");\r\n");
      out.write("\r\n");
      out.write("    if (event.target === createModal) {\r\n");
      out.write("        closeCreateModal();\r\n");
      out.write("    }\r\n");
      out.write("    if (event.target === updateModal) {\r\n");
      out.write("        closeUpdateModal();\r\n");
      out.write("    }\r\n");
      out.write("    if (event.target === deleteModal) {\r\n");
      out.write("        cancelDelete();\r\n");
      out.write("    }\r\n");
      out.write("};\r\n");
      out.write("\r\n");
      out.write("// ==================== Keyboard Navigation ====================\r\n");
      out.write("\r\n");
      out.write("document.addEventListener(\"keydown\", function (event) {\r\n");
      out.write("    if (event.key === \"Escape\") {\r\n");
      out.write("        closeCreateModal();\r\n");
      out.write("        closeUpdateModal();\r\n");
      out.write("        cancelDelete();\r\n");
      out.write("    }\r\n");
      out.write("});\r\n");
      out.write("</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
