/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.112
 * Generated at: 2025-12-06 23:10:59 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.api;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;
import java.sql.*;

public final class bookHandler_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {


    /**
     * Busca todos os livros do banco de dados
     * @param conn ConexÃ£o com o banco
     * @param stmt Statement da conexÃ£o
     * @return ResultSet com os livros
     */
    ResultSet readBook(Connection conn, Statement stmt, String url) throws Exception {
        String query = "SELECT * FROM book";
        return stmt.executeQuery(query);
    }

    /**
     * Cria um novo livro no banco de dados
     * @param conn ConexÃ£o com o banco
     * @param image URL da imagem
     * @param name Nome do livro
     * @param description DescriÃ§Ã£o do livro
     * @param content ConteÃºdo do livro
     * @return Mensagem de sucesso ou erro
     */
    String createBook(
        Connection conn, 
        String image, 
        String name, 
        String description, 
        String content
    ) throws Exception {
        String result = "";

        try {
            if (conn != null && !conn.isClosed()) {
                String sql = "INSERT INTO book (image, name, description, content) VALUES (?, ?, ?, ?)";
                try (PreparedStatement pstmt = conn.prepareStatement(sql)) {
                    pstmt.setString(1, image);
                    pstmt.setString(2, name);
                    pstmt.setString(3, description);
                    pstmt.setString(4, content);

                    int rowsAffected = pstmt.executeUpdate();

                    if (rowsAffected > 0) {
                        result = "Livro inserido com sucesso!";
                    } else {
                        result = "Nenhum livro foi inserido.";
                    }
                }
            } else {
                result = "ConexÃ£o com o banco nÃ£o estÃ¡ disponÃ­vel.";
            }
        } catch (SQLException e) {
            result = "Erro ao inserir livro: " + e.getMessage();
        }
        return result;
    }

    /**
     * Atualiza um livro no banco de dados
     * @param conn ConexÃ£o com o banco
     * @param id ID do livro
     * @param image URL da imagem
     * @param name Nome do livro
     * @param description DescriÃ§Ã£o do livro
     * @param content ConteÃºdo do livro
     * @return Mensagem de sucesso ou erro
     */
    String updateBook(
        Connection conn,
        int id,
        String image,
        String name,
        String description,
        String content
    ) throws Exception {
        String result = "";

        try {
            if (conn != null && !conn.isClosed()) {
                String sql = "UPDATE book SET image = ?, name = ?, description = ?, content = ? WHERE id = ?";
                try (PreparedStatement pstmt = conn.prepareStatement(sql)) {
                    pstmt.setString(1, image);
                    pstmt.setString(2, name);
                    pstmt.setString(3, description);
                    pstmt.setString(4, content);
                    pstmt.setInt(5, id);

                    int rowsAffected = pstmt.executeUpdate();

                    if (rowsAffected > 0) {
                        result = "Livro atualizado com sucesso!";
                    } else {
                        result = "Nenhum livro foi atualizado.";
                    }
                }
            } else {
                result = "ConexÃ£o com o banco nÃ£o estÃ¡ disponÃ­vel.";
            }
        } catch (SQLException e) {
            result = "Erro ao atualizar livro: " + e.getMessage();
        }
        return result;
    }

    /**
     * Deleta um livro do banco de dados
     * @param conn ConexÃ£o com o banco
     * @param id ID do livro
     * @return Mensagem de sucesso ou erro
     */
    String deleteBook(Connection conn, int id) throws Exception {
        String result = "";

        try {
            if (conn != null && !conn.isClosed()) {
                String sql = "DELETE FROM book WHERE id = ?";
                try (PreparedStatement pstmt = conn.prepareStatement(sql)) {
                    pstmt.setInt(1, id);

                    int rowsAffected = pstmt.executeUpdate();

                    if (rowsAffected > 0) {
                        result = "Livro deletado com sucesso!";
                    } else {
                        result = "Nenhum livro foi deletado.";
                    }
                }
            } else {
                result = "ConexÃ£o com o banco nÃ£o estÃ¡ disponÃ­vel.";
            }
        } catch (SQLException e) {
            result = "Erro ao deletar livro: " + e.getMessage();
        }
        return result;
    }

    /**
     * Busca um livro especÃ­fico por ID
     * @param conn ConexÃ£o com o banco
     * @param id ID do livro
     * @return ResultSet com os dados do livro
     */
    ResultSet getBookById(Connection conn, int id) throws Exception {
        String query = "SELECT * FROM book WHERE id = ?";
        PreparedStatement pstmt = conn.prepareStatement(query);
        pstmt.setInt(1, id);
        return pstmt.executeQuery();
    }

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/src/config/connect.jsp", Long.valueOf(1765062111748L));
    _jspx_dependants.put("/src/repository/book/bookOperations.jsp", Long.valueOf(1765062486598L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(6);
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("application/json; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");

    String url = "jdbc:sqlite:C:/Users/daniel.resende_judit/Downloads/apache-tomcat-9.0.112-windows-x64/apache-tomcat-9.0.112/webapps/examples/banco3.db";
    Connection conn = null;
    Statement stmt = null;
    Class.forName("org.sqlite.JDBC");
    conn = DriverManager.getConnection(url);
    stmt = conn.createStatement();

    Connection connCreate = DriverManager.getConnection(url);
    Statement stmtCreate = conn.createStatement();

      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("\r\n");
      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("\r\n");

    // Set response type to JSON
    response.setContentType("application/json; charset=UTF-8");

    String action = request.getParameter("action");
    String result = "";

    try {
        if ("create".equals(action)) {
            String image = request.getParameter("image");
            String name = request.getParameter("name");
            String description = request.getParameter("description");
            String content = request.getParameter("content");

            result = createBook(connCreate, image, name, description, content);
            
            // Close connections
            if (stmtCreate != null) stmtCreate.close();
            if (connCreate != null) connCreate.close();

        } else if ("update".equals(action)) {
            int id = Integer.parseInt(request.getParameter("id"));
            String image = request.getParameter("image");
            String name = request.getParameter("name");
            String description = request.getParameter("description");
            String content = request.getParameter("content");

            result = updateBook(connCreate, id, image, name, description, content);
            
            // Close connections
            if (stmtCreate != null) stmtCreate.close();
            if (connCreate != null) connCreate.close();

        } else if ("delete".equals(action)) {
            int id = Integer.parseInt(request.getParameter("id"));

            result = deleteBook(connCreate, id);
            
            // Close connections
            if (stmtCreate != null) stmtCreate.close();
            if (connCreate != null) connCreate.close();

        } else {
            result = "Ação inválida";
        }

        // Return JSON response
        out.println("{\"message\": \"" + result.replace("\"", "\\\"") + "\", \"success\": true}");

    } catch (Exception e) {
        // Return error response
        out.println("{\"message\": \"Erro: " + e.getMessage().replace("\"", "\\\"") + "\", \"success\": false}");

        // Close connections in case of error
        try {
            if (stmtCreate != null) stmtCreate.close();
            if (connCreate != null) connCreate.close();
        } catch (SQLException se) {
            // Ignore close errors
        }
    }

      out.write('\r');
      out.write('\n');
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
